export const styles = {

    FlexStyle: {
    minH: "100vh",
    mt: { base: "-20px", md: "-80px" },
    justify: "flex-start",
    bg: "white",
    px: { base: 4, md: 12, lg: 60 },
    py: { base: 6, md: 10 },
  },
  CardContainer: {
    borderWidth: "1px",
    borderRadius: "xl",
    p: 6,
    textAlign: "center",
    cursor: "pointer",
    boxShadow: "md",
    transition: "all 0.3s",
    _hover: { boxShadow: "xl", transform: "scale(1.05)" },
  },
  ImageStyle: {
    boxSize: { base: "200px", lg: "170px" },
    objectFit: "cover",
    borderRadius: "full",
    mx: "auto",
    mt: { base: "30px", md: "-35px", lg: "-35px" },
    mb: { base: "-30px", md: "-30px", lg: "-10px" },
  },
  HobbieImageStyle: {
    boxSize: { base: "80px", lg: "100px" },
    objectFit: "cover",
    borderRadius: "full",
    mx: "auto",
    mt: "5px",
    mb: "5px",
  },
  container: {
    position: "relative",
    p: 0,
    maxW: "4xl",
    mx: { base: "auto", md: "auto" },
  },
  sidebarContainer: {
    direction: { base: "row", md: "column" },
    w: { base: "100%", md: "250px", lg: "320px" },
    h: { base: "60px", md: "130vh" },
    bg: "#1B1E23",
    color: "white",
    p: 4,
    position: "fixed",
    top: 0,
    left: 0,
    align: "center",
    justify: { base: "space-between", md: "flex-start" },
    zIndex: 1000,
  },
  titleSection: {
    border: { base: 0, md: "2px solid #ff7600" },
    borderRadius: "2xl",
    p: 4,
    mt: { base: 0, md: "100px" },
    mb: { base: 0, md: 8 },
    w: "100%",
    bg: { base: "transparent", md: "#1B1E23" },
    boxShadow: { base: "none", md: "lg" },
  },
  desktopTitleBox: {
    display: { base: "none", md: "block" },
    textAlign: "center",
  },

  desktopTitleText: {
    fontSize: "md",
    fontWeight: "extrabold",
    color: "#ff7600",
    letterSpacing: "wide",
  },
  desktopSubtitleText: {
    fontSize: "sm",
    color: "gray.300",
    fontStyle: "italic",
  },
  desktopNavBox: {
    display: { base: "none", md: "block" },
    w: "100%",
  },
  desktopNavLink: {
    align: "center",
    pl: 2,
    mb: 5,
    w: "100%",
    fontSize: "sm",
    fontWeight: "medium",
    color: "gray.300",
    _hover: { color: "#ff7600", transform: "translateX(4px)" },
    transition: "all 0.2s ease",
  },
  mobileMenuBox: {
    display: { base: "block", md: "none" },
  },
  menuList: {
    bg: "gray.800",
    borderColor: "gray.700",
    color: "gray.300",
    minW: "200px",
    mr: "-15px",
  },
  menuItem: {
    bg: "#212429",
    color: "gray.300",
    fontSize: "xs",
    fontWeight: "medium",
    _hover: {
      color: "#ff7600",
      bg: "gray.800",
      transform: "translateX(4px)",
    },
    _focus: { bg: "#1B1E23" },
    w: "100%",
    py: 3,
    borderBottom: "1px solid",
    borderColor: "gray.600",
  },
};
